version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_ENV=production
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud/application_default_credentials.json
    volumes:
      # Mount Google Cloud credentials
      - ~/.config/gcloud:/app/gcloud:ro
      # Mount a volume for photo storage if needed
      - photo_data:/app/photos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: photos-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lyfe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  photo_data:
  postgres_data: 