"""Add path field to Photo model

Revision ID: 7da03bb53cf3
Revises: 
Create Date: 2025-05-26 18:05:40.619802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da03bb53cf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=1000), nullable=True))

    # Update existing records to have a default path value
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE photos SET path = 'uploaded_via_web' WHERE path IS NULL"))
    
    # Now make the column NOT NULL
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.alter_column('path', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
